version: "2.0.0-testing.5"
image: ghcr.io/riddix/home-assistant-matter-hub-addon-testing
slug: hamh-testing
name: Home-Assistant-Matter-Hub (Testing)
description: "\U0001F9EA TESTING VERSION - For Matter.js debugging only! Contains debug logging without ACL workaround patch."
url: https://github.com/riddix/home-assistant-matter-hub/tree/testing-matterjs
panel_icon: mdi:bug
panel_title: Matter Hub Testing
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: debug
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
